### ISSUE TITLE
OneNote links in README not functional

### ISSUE THREAD

**Issue by RowanAldean** [ChuksAjeh/learn#1]
Looks like the OneNote book is private - unsure if that's intentional or not :)

**Comment by ChuksAjeh** [comment]
New OneNote requires I use the person's email to share it with them specifically. I have amended the READme to reflect this. I have given you access.

**Comment by RowanAldean** [comment]
Awesome - im not too bothered by it tbh. Just making you aware for future ref :) README link works but the para is duplicated twice nun major 👌🏽 Goodluck with this project
